### ISSUE TITLE
About Ream generator

### ISSUE THREAD

**Issue by unix** [egoist/ream#27]
Hi, @egoist , this repo is cool!

We can use [func](https://github.com/unix/func) to create Ream generator?
If so, I'll take care of it for generator app.

**Comment by egoist** [comment]
Actually I want a library that supports nested commands like `git remote prune origin` so I can implement `ream generate page hello`, `ream generate api_route graphql --ts`

https://github.com/yargs/yargs/blob/master/docs/advanced.md#example-command-hierarchy-using-commanddir

**Comment by egoist** [comment]
I guess it's fine to use `func` to implement `create-ream-app` though, there won't be any subcommands.

**Comment by unix** [comment]
well, agreed.
