### ISSUE TITLE
Plugin for blogging!

### ISSUE THREAD

**Issue by egoist** [egoist/ream#8]
Similar to [fs-router-plugin](https://egoistian.com/unvue/#/plugin/fs-router) ([source code](https://github.com/egoist/unvue/blob/master/plugins/fs-router.js)), a blog-plugin would be awesome, it reads `source/**/*.md` and maps them into routes! saying `./source/2015/hello-world.md` becomes `/2015/hello-world`.

**Comment by znck** [comment]
I'll try this weekend.

**Comment by egoist** [comment]
@znck nice, and that could be published as an independent package 😄 cuz I can imagine that will use several 3rd-party libraries.

**Comment by egoist** [comment]
Cool, and now we have a free org account for publishing scoped package https://www.npmjs.com/org/unvue

**Comment by egoist** [comment]
Here it is, https://github.com/egoist/ream-blog-plugin but we still need to improve it.
